---
title: "Activities"
output: html_document
---

<br/>
<br/>

### Teaching
<br/>

- 2022. Utrecht University, Applied Data Science MA Thesis Project, *Co-supervising final thesis projects of master students in the Applied Data Science program*
<br/>
<br/>

- 2021. Utrecht University, BA Thesis Project, *Supervising final thesis projects of bachelor students in the Sociology program*
<br/>
<br/>

- 2020 - 2022.  Utrecht University, Advanced Sociological Theory: Modelling Social Interaction, *Leading the seminar groups*  
<br/>  
<br/>  
 

### Professional service and affiliations
<br/>

- **Vice-chair**, [Young Complexity Researchers Utrecht (YCRU)](https://www.uu.nl/en/research/centre-for-complex-systems-studies-ccss/about-us/young-complexity-researchers-utrecht-ycru), Academic year
2022 - 2023.
<br/>
<br/>

- **Student Representative**, ASA [Rationality and Society section](https://sites.google.com/site/rationalityandsocietysection/?pli=1), Academic year
2022 - 2023.
<br/>
<br/>

- **Junior member**, [Centre for Complex Systems Studies (CCSS)](https://www.uu.nl/en/research/centre-for-complex-systems-studies-ccss/), Utrecht University. 
<br/>
<br/>
<br/>  
<br/>  
 


### Additional Training
<br/>

- 2023. Graduate Workshop in Computational Social Science Modelling and Complexity, *Organized by the Santa Fe Institute.*
<br/>
<br/>

- 2023. Visiting Scholar, *Hosted by dr. Mirta Galesic, Santa Fe Institute, Santa Fe.*
<br/>
<br/>

- 2022. Visiting Scholar, *Hosted by dr. Milena Tsvetkova, Department of Methodology, London School of Economics and Political Science (LSE), London.*
<br/>
<br/>

- 2022. Complexity-GAINs International Summer School, *Co-hosted by the Santa Fe Institute, the Max Planck Institute for Mathematics in the Sciences and Hamburg University of Technology (Germany), Complexity Science Hub Vienna (Austria), Quantitative Life Sciences, International Center for Theoretical Physics (Italy), and Institute for Advanced Studies, University of Amsterdam (Netherlands).*
<br/>
<br/>

- 2021. CNRS Thematic School: Agent-based Modelling in Sociology with NetLogo, *Co-hosted by the National Center for Scientific Research (CNRS) and the Sorbonne Research the Sorbonne Research Group in the Methods of Sociological Analysis (GEMASS)*
<br/>
<br/>

- 2021. Medici Summer School: Cooperation in organizing and innovating, *Co-hosted by the University of Bologna, HEC Paris and MIT Sloan School of Management*
<br/>
<br/>

- 2021. Summer Institute in Computational Social Science (SICSS) London, *Co-Hosted by the University College London, London School of Economics, Imperial College London, Greenwich University, and City, University of London*

 <br/>  
 <br/> 
 
### Invited talks
<br/>

- 2023. Signals of Belonging: Emergence of Signalling Norms as Facilitators of Parochial Cooperation, *Cooperative Relations Seminar, Department of Sociology, Utrecht University*
<br/>
<br/>

- 2023. Text Mining in Social Sciences: A Methods Overview, *DYSTENA Workshop: Gaining Insights into Social Media Discourse by Combining Text and Network Analyses, Online*
<br/>
<br/>


- 2023. Minority Group Size Moderates Inequity-Reducing Strategies in Homophilic Networks, *Centre for Complex Systems Studies (CCSS), Utrecht University*
<br/>
<br/>

- 2023. “I Heard it on the (Silk)Road”: Who Introduces
Innovations in Online Communities?, *Summer Institute in Computational Social Science (SICSS) London*
<br/>
<br/>

<br/>  
<br/> 
 
### Conference and Workshop Presentations
<br/>


- 2023.	“I Heard it on the (Silk)Road”: Structural and Cultural Pathways to Novelty Introduction in an Online Community, *118th Annual Meeting of the American Sociological Association, Philadelphia*
<br/>
<br/>

- 2023.	Governing Through Gossip: The Role of Informal Communication in Reputation-Based Online Markets, *118th Annual Meeting of the American Sociological Association, Philadelphia*
<br/>
<br/>


- 2023.	Governing Through Gossip: The Role of Informal Communication in Reputation-Based Online Markets, *15th Annual Conference of the International Network of Analytical Sociologists (INAS), Princeton University, Princeton*
<br/>
<br/>


- 2023.	The Moral Embeddedness of Cryptomarkets: Text Mining Feedback on Economic Exchanges on the Dark Web, *International Meeting on Experimental and Behavioral Social Sciences (IMEBESS), Lisbon*
<br/>
<br/>


- 2022. Computational Text Analysis for Sociology – Opportunities and Challenges, *ODISSEI Conference for Social Science in the Netherlands 2022, Utrecht*
<br/>
<br/>

- 2022. Does the Grapevine Still Matter? The Importance of Gossip in the Presence of Formalized Reputation Measures in Online Markets, *International Conference on Social Dilemmas (ICSD) 2022, University of Copenhagen, Copenhagen*
<br/>
<br/>

- 2022. Mapping Individuals’ Internal States from Tweets and Feedback Texts: A Systematic Evaluation of Text Mining Methods for Short Texts, *14th Annual Conference of the International Network of Analytical Sociologists (INAS), European University Institute, Florence*
<br/>
<br/>

- 2021. Mining Everyday Texts for Sociologically Relevant Phenomena: Evidence from Online Market Exchanges, *15th ESA Conference*, *Online*
<br/>
<br/>

- 2021. Positive Reputation Bias in Cryptomarkets: Validating Quantitative Ratings with Automatic Analyses of Feedback Texts, *IV ISA Forum of Sociology*, *Online*
<br/>
<br/>


- 2020. Presentation: Motives for leaving feedback after cryptomarket transactions - Evidence from automatic text analysis, *Text Analysis in Economics and the Social Sciences Workshop, University of East Anglia*, *Online*
 <br/>
 <br/>


